install:
    - ps: choco install -y -r hg
# See https://github.com/appveyor/ci/issues/1745
    - ps: Set-Content -Path "gradle.properties" -Value "org.gradle.daemon=false"

build_script:
    - gradlew.bat build
