language: java

matrix:
    include:
        - os: linux
          jdk: openjdk8
        - os: osx
          osx_image: xcode8.3
        - os: osx
          osx_image: xcode10.1

script:
    - ./gradlew build

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gradle jacocoTestReport coveralls; fi
