language: java

matrix:
    include:
        - os: osx
          osx_image: xcode10.1

script:
    - ./gradlew build --stacktrace --scan

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gradle jacocoTestReport coveralls; fi
